### ISSUE TITLE
Reorganize modules in a package and rename notebooks

### ISSUE THREAD

**Issue by jccaicedo** [broadinstitute/segmentation_experiments#13]
Create a directory called `functions` (for now) and move all the Python modules (.py files) there. Then make sure that all your notebooks run by updating the imports from `import xxx` to `import functions.xxx`. Perhaps you need to create an empty `__init__.py` file.

Rename your notebooks with a two digit number to keep track of the order in which they should be run. For instance: `01_preprocessing.ipynb` and `02_tensorflow_experiment.ipynb`, and so on.

**Comment by eric-bueno** [comment]
issue has been resolved in commit 91526104a06e504b99c2e0d81120ba16682767fa
