### ISSUE TITLE
Reduce load_COLOR_data() functions to a single function

### ISSUE THREAD

**Issue by jccaicedo** [broadinstitute/segmentation_experiments#14]
There are 4 functions that have pretty much identical code in the `load_all_data` module, except some names that could be parameterized. Can you reduce the code to a single function that receives these names as parameter and returns the expected data?

The four functions are:
- [load_purp_data](https://github.com/broadinstitute/segmentation_experiments/blob/1342d0224f045448ef0ccfb32e8a03284e9d2b7f/load_all_data.py#L53)
- [load_pink_data](https://github.com/broadinstitute/segmentation_experiments/blob/1342d0224f045448ef0ccfb32e8a03284e9d2b7f/load_all_data.py#L73)
- [load_default_data](https://github.com/broadinstitute/segmentation_experiments/blob/1342d0224f045448ef0ccfb32e8a03284e9d2b7f/load_all_data.py#L92)
- [load_bw_data](https://github.com/broadinstitute/segmentation_experiments/blob/1342d0224f045448ef0ccfb32e8a03284e9d2b7f/load_all_data.py#L112)

**Comment by eric-bueno** [comment]
make this function generic: specify the color you want when calling the function

**Comment by eric-bueno** [comment]
This issue has been resolved in commit: e78c2692745abebead01d6b0ac914a283e8117e0
