### ISSUE TITLE
Reclassify images in CSV file

### ISSUE THREAD

**Issue by eric-bueno** [broadinstitute/segmentation_experiments#21]
Reclassify image labels in the CSV file to reflect the color of the image

**Comment by jccaicedo** [comment]
All the images have been re-classified by hand. The new `.csv` file can be found here: `/raid/data/BBBC038/fix_training_classifications.csv`. The file has three columns:  Image_Name, Color, Type. Here is the distribution of images by color:

<img width="379" alt="Screen Shot 2020-07-24 at 5 47 24 PM" src="https://user-images.githubusercontent.com/7527135/88437906-80272a80-cdd5-11ea-8669-80d03cce3996.png">

And this is by the old type annotation:
<img width="387" alt="Screen Shot 2020-07-24 at 5 47 35 PM" src="https://user-images.githubusercontent.com/7527135/88437930-8e754680-cdd5-11ea-9f28-6afdae5b13b8.png">

@eric-bueno can you check if this is correct now?

**Comment by eric-bueno** [comment]
Issue has been resolved in commit c3c7b2ab2a32c8bc1fa8978700def3f9c7e439f4
