### ISSUE TITLE
Implement an image rescaling function

### ISSUE THREAD

**Issue by jccaicedo** [broadinstitute/segmentation_experiments#32]
The goal is to have a function that gets an image, the ground truth composite and the target average object size as parameters and returns a new image with a new composite both rescaled to a new size that approximates the requested average object size. It would look like this:

```
rescaled_image, rescaled_composite = FUNCTION(image, composite, target_size)
```

The calculations that the function needs to make are:
- Current average object size.
- Ratio of current size (`cs`) and target object size (`ts`) as follows: `ratio=cs/ts`
- Use the `skimage.transform.rescale` function to transform the image and the composite
- Return the result

Verify visually and numerically that the object size of the rescaled images is close to the target size.

**Comment by eric-bueno** [comment]
Issue has been resolved in commit f48e7310905b0eeaf03aaee15442ccd99679d86a
